version: "3"
services:
  app:
    restart: always
    build:
      # Use the Dockerfile in the current folder
      context: .
    ports:
      - 80:80
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: jkmapdev1
      MARIADB_PASSWORD: proximity
      MARIADB_ROOT_PASSWORD: proximity
      MARIADB_DATABASE: if0_36069118_dbsquest
    ports:
      - 3307:3306
    volumes:
      - ./volumes/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3000:80
    environment:
      PMA_ARBITRARY: 1
